stages:
  - clean          # List of stages for jobs, and their order of execution
  - test

before_script:
  - apk update && apk add maven && apk add make && apk add openjdk11 && apk add docker && apk add docker-compose

clean-job:       # This job runs in the build stage, which runs first.
  stage: clean
  script:
    - echo "Cleaning all code artifacts..."
    - make clean

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - make driver_install
    - make test
