all: clean validate initialize compile test verify

clean:
	#echo "clean in progress"
	mvn clean
	#echo "clean complete"

validate:
	#echo "validate in progress"
	mvn validate
	#echo "validate complete"

initialize:
	#echo "initialize in progress"
	mvn initialize
	#echo "initialize complete"

compile:
	#echo "Compile in progress"
	mvn compile
	#echo "Compile complete"

test:
	#echo "test in progress"
	mvn test
	#echo "test complete"

verify:
	#echo "verify in progress"
	mvn verify
	#echo "verify complete"